[features]
seeds = false
skip-lint = false
[programs.devnet]
unicus_ts = "5d1RwrEGymHuXAkHQTo7CAkBDhrVDsxUJs8b6jgtSFie"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/varsha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
